### ISSUE TITLE
is it compatible with Mono framework ?

### ISSUE THREAD

**Issue by sushmakoulgi** [tmds/Tmds.MDns#8] opened 2016-10-19 07:11 UTC
is it compatible with Mono framework ?

**Comment by tmds** [comment] 2016-10-19 08:36
I ran it on mono before, lately I have been using .NET Core.
Give it a try. If it doesn't work, we'll fix it.

**Comment by hooby3dfx** [comment] 2016-10-19 22:04
Wow, perfect timing!
I am getting this Exception:
System.Net.Sockets.SocketException: Operation not supported
  at System.Net.Sockets.Socket.SetSocketOption (System.Net.Sockets.SocketOptionLevel optionLevel, System.Net.Sockets.SocketOptionName optionName, System.Int32 optionValue) [0x00067] in /private/tmp/source-mono-4.6.0-c8sr0/bockbuild-mono-4.6.0-branch-c8sr0/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/System/System.Net.Sockets/Socket.cs:3205
  at Tmds.MDns.NetworkInterfaceHandler.Enable () [0x0005b] in Tmds.MDns-master/Tmds/MDns/NetworkInterfaceHandler.cs:65
  at Tmds.MDns.ServiceBrowser.CheckNetworkInterfaceStatuses (System.Collections.Generic.Dictionary`2[TKey,TValue] interfaceHandlers) [0x0011e] in Tmds.MDns-master/Tmds/MDns/ServiceBrowser.cs:264
  at Tmds.MDns.ServiceBrowser+<StartBrowsing>c__AnonStorey5.<>m__0 (System.Object s, System.EventArgs e) [0x0000d] in Tmds.MDns-master/Tmds/MDns/ServiceBrowser.cs:222
  at System.Net.NetworkInformation.MacNetworkChange.add_NetworkAddressChanged (System.Net.NetworkInformation.NetworkAddressChangedEventHandler value) [0x00000] in /private/tmp/source-mono-4.6.0-c8sr0/bockbuild-mono-4.6.0-branch-c8sr0/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/System/System.Net.NetworkInformation/NetworkChange.cs:218
  at System.Net.NetworkInformation.NetworkChange.add_NetworkAddressChanged (System.Net.NetworkInformation.NetworkAddressChangedEventHandler value) [0x00024] in /private/tmp/source-mono-4.6.0-c8sr0/bockbuild-mono-4.6.0-branch-c8sr0/profiles/mono-mac-xamarin/build-root/mono-x86/mcs/class/System/System.Net.NetworkInformation/NetworkChange.cs:69
  at Tmds.MDns.ServiceBrowser.StartBrowsing (System.Threading.SynchronizationContext synchronizationContext) [0x0005c] in Tmds.MDns-master/Tmds/MDns/ServiceBrowser.cs:224
  at Tmds.MDns.ServiceBrowser.StartBrowse (System.Collections.Generic.IEnumerable`1[T] serviceTypes, System.Threading.SynchronizationContext synchronizationContext) [0x00026] in Tmds.MDns-master/Tmds/MDns/ServiceBrowser.cs:46
  at Tmds.MDns.ServiceBrowser.StartBrowse (System.Collections.Generic.IEnumerable`1[T] serviceTypes, System.Boolean useSynchronizationContext) [0x0000f] in Tmds.MDns-master/Tmds/MDns/ServiceBrowser.cs:75
  at Tmds.MDns.ServiceBrowser.StartBrowse (System.String serviceType, System.Boolean useSynchronizationContext) [0x0000d] in Tmds.MDns-master/Tmds/MDns/ServiceBrowser.cs:85
  at ConsoleApplication1.Program.DiscoveryTest () [0x00084] in Program.cs:190

**Comment by sushmakoulgi** [comment] 2016-10-20 04:42
Same here.

**Comment by tmds** [comment] 2016-10-20 04:45
@sushmakoulgi you are also using a Mac?
@sushmakoulgi @hooby3dfx what version of mono are you using?

**Comment by sushmakoulgi** [comment] 2016-10-20 07:42
Yes  , I am also using mac 10.11 and mono version 4.x

**Comment by tmds** [comment] 2016-10-20 08:53
It seems the exception is thrown on this line:
`_socket.SetSocketOption(SocketOptionLevel.IP, SocketOptionName.MulticastInterface, IPAddress.HostToNetworkOrder(_index));
`
This sets the interface where packets should be sent. You may want to try commenting this line, packets will be sent to the default interface then. On a system with one active interface (most systems), this will be fine.

I would be interested in knowing the call made to the kernel which returns unsupported. On Linux you can do this using `strace -f -e setsockopt <command>`. It seems something similar can be done on Mac using: `dtruss -f -t setsockopt <command>`. Can you send the output?

**Comment by hooby3dfx** [comment] 2016-10-20 19:18
Thanks - commenting out that line works.
What should I try in place of <command>?

**Comment by tmds** [comment] 2016-10-20 19:33
`<command>` is what you use to start your console application on the command-line.

**Comment by hooby3dfx** [comment] 2016-10-20 19:49
```
42211/0x21e2fbf:  setsockopt(0xA, 0xFFFF, 0x4)		 = 0 0
42211/0x21e2fbf:  setsockopt(0xA, 0xFFFF, 0x4)		 = 0 0
42211/0x21e2fbf:  setsockopt(0xA, 0xFFFF, 0x200)		 = 0 0
42211/0x21e2fbf:  setsockopt(0xA, 0x0, 0x9)		 = 0 0
42211/0x21e2fbf:  setsockopt(0xA, 0x0, 0xC)		 = 0 0
42211/0x21e2fbf:  setsockopt(0xA, 0x0, 0xA)		 = 0 0
42211/0x21e2fbf:  setsockopt(0xB, 0xFFFF, 0x4)		 = 0 0
42211/0x21e2fbf:  setsockopt(0xB, 0xFFFF, 0x4)		 = 0 0
42211/0x21e2fbf:  setsockopt(0xB, 0xFFFF, 0x200)		 = 0 0
42211/0x21e2fbf:  setsockopt(0xB, 0x0, 0x9)		 = -1 Err#102
```

**Comment by tmds** [comment] 2016-10-20 20:06
Thanks. The exception may be caused because multicast is not enabled on a network interface.

Can you Console.WriteLine NetworkInterface.Name NetworkInterface.Id NetworkInterface.SupportsMulticast before the SetSocketOption that fails?
Can you also check whether the output of the `ifconfig` command contains MULTICAST for that interface?

**Comment by hooby3dfx** [comment] 2016-10-20 20:20
en0 is my Wi-Fi which I am using.

.net debug output:
```
en0, en0, True
en1, en1, False
en2, en2, False
p2p0, p2p0, True
bridge0, bridge0, True
awdl0, awdl0, True
utun0, utun0, True
utun1, utun1, True
```
ifconfig output:
```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=3<RXCSUM,TXCSUM>
	inet6 ::1 prefixlen 128 
	inet 127.0.0.1 netmask 0xff000000 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=1<PERFORMNUD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 34:36:3b:cc:72:36 
	inet6 fe80::3636:3bff:fecc:7236%en0 prefixlen 64 scopeid 0x4 
	inet 192.168.86.155 netmask 0xffffff00 broadcast 192.168.86.255
	nd6 options=1<PERFORMNUD>
	media: autoselect
	status: active
en1: flags=963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX> mtu 1500
	options=60<TSO4,TSO6>
	ether 72:00:08:74:92:80 
	media: autoselect <full-duplex>
	status: inactive
en2: flags=963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX> mtu 1500
	options=60<TSO4,TSO6>
	ether 72:00:08:74:92:81 
	media: autoselect <full-duplex>
	status: inactive
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	ether 06:36:3b:cc:72:36 
	media: autoselect
	status: inactive
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 36:36:3b:cc:11:00 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 5 priority 0 path cost 0
	member: en2 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 6 priority 0 path cost 0
	nd6 options=1<PERFORMNUD>
	media: <unknown type>
	status: inactive
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	ether be:54:12:71:94:38 
	inet6 fe80::bc54:12ff:fe71:9438%awdl0 prefixlen 64 scopeid 0x9 
	nd6 options=1<PERFORMNUD>
	media: autoselect
	status: active
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet6 fe80::2aa0:a8ba:e7ad:8760%utun0 prefixlen 64 scopeid 0xa 
	nd6 options=1<PERFORMNUD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet6 fe80::f419:a588:7938:ef79%utun1 prefixlen 64 scopeid 0xb 
	nd6 options=1<PERFORMNUD>
```

**Comment by tmds** [comment] 2016-10-21 07:07
Thanks. This patch should fix the issue: https://github.com/tmds/Tmds.MDns/pull/9/files.
Can you verify?

**Comment by sushmakoulgi** [comment] 2016-10-21 07:37
Thanks @tmds . It worked !

**Comment by tmds** [comment] 2016-10-21 14:51
I will close the issue once @hooby3dfx confirms it is also working for him.
Feel free to add a star to the project! :)

**Comment by sushmakoulgi** [comment] 2016-11-04 13:18
Hi Tmds, 
 we are observing one issue while monitoring packets in Mac using Mono framework. when  Wifi is on and  devices sending Mdns packets are over ethernet. we get exception at
send function(line no 136)  in networkinterfaceHandler.cs . this is being called by OnQueryTimerElapsed. 

Exception says "The requested address is not valid in its context"

**Comment by tmds** [comment] 2016-11-04 14:26
@sushmakoulgi which interface throws the exception? does it have a an ipv4 address?

**Comment by sushmakoulgi** [comment] 2016-11-08 05:59
It is not reproducible all the time. I will let you know once I get it again. Thanks for the support @tmds

**Comment by sushmakoulgi** [comment] 2016-11-09 09:42
looks like issue is in Socket Option's bind function 
NetworkInterfaceHandler.cs -->Enable () function --> 
_socket.Bind(new IPEndPoint(IPAddress.Any, IPv4EndPoint.Port));

When we comment this line in Mac, Discovery works fine else, with both Ethernet and Wifi network adapter ON, library was not catching up the mdns packets. 

We have added following check for this piece of code. 

 if (Environment.OSVersion.Platform != PlatformID.MacOSX && Environment.OSVersion.Platform != PlatformID.Unix)
                    {
                        _socket.Bind(new IPEndPoint(IPAddress.Any, IPv4EndPoint.Port));
                    }

**Comment by tmds** [comment] 2016-11-09 10:17
@sushmakoulgi the Bind ensures only packets destined for that specific port are received on the socket.
Is this correct: by uncommenting the Bind, the Send method is no longer throwing?
You mentioned the issue is not reproducible all the time. Does this mean the code is sometimes working?

**Comment by sushmakoulgi** [comment] 2016-11-10 05:30
Yes. We were trying multiple options , so was not sure, what was throwing exception. With this fix, we are not getting this exception also.

**Comment by tmds** [comment] 2016-11-13 19:39
@sushmakoulgi @hooby3dfx I will close this issue. I included the multicast check in the library. Although  excluding the Bind call fixes an issue for @sushmakoulgi I am not going to include it because I cannot relate this 'fix' to documented behavior or source code (e.g. Mac/BSD kernel).

**Closed by tmds** 2016-11-13 19:39 UTC
