### ISSUE TITLE
Trying to get it to run in Unity

### ISSUE THREAD

**Issue by josephnarai** [tmds/Tmds.MDns#30] opened 2019-04-09 08:10 UTC
I successfully created a windows console app that works fine.

I've now imported into Unity (the platform I need to run this on), and I'm getting a null exception:

EntryPointNotFoundException: CreateNLSocket
System.Net.NetworkInformation.LinuxNetworkChange.EnsureSocket () (at <3845a180c26b4889bc2d47593a665814>:0)
System.Net.NetworkInformation.LinuxNetworkChange.Register (System.Net.NetworkInformation.NetworkAddressChangedEventHandler d) (at <3845a180c26b4889bc2d47593a665814>:0)
System.Net.NetworkInformation.LinuxNetworkChange.add_NetworkAddressChanged (System.Net.NetworkInformation.NetworkAddressChangedEventHandler value) (at <3845a180c26b4889bc2d47593a665814>:0)
System.Net.NetworkInformation.NetworkChange.add_NetworkAddressChanged (System.Net.NetworkInformation.NetworkAddressChangedEventHandler value) (at <3845a180c26b4889bc2d47593a665814>:0)
Tmds.MDns.ServiceBrowser.StartBrowsing (System.Threading.SynchronizationContext synchronizationContext) (at Assets/Plugins/Tmds.MDns/ServiceBrowser.cs:224)
Tmds.MDns.ServiceBrowser.StartBrowse (System.Collections.Generic.IEnumerable`1[T] serviceTypes, System.Threading.SynchronizationContext synchronizationContext) (at Assets/Plugins/Tmds.MDns/ServiceBrowser.cs:45)
Tmds.MDns.ServiceBrowser.StartBrowse (System.Collections.Generic.IEnumerable`1[T] serviceTypes, System.Boolean useSynchronizationContext) (at Assets/Plugins/Tmds.MDns/ServiceBrowser.cs:74)
Tmds.MDns.ServiceBrowser.StartBrowse (System.String serviceType, System.Boolean useSynchronizationContext) (at Assets/Plugins/Tmds.MDns/ServiceBrowser.cs:84)
AES70Manager.Start () (at Assets/Scripts/AES70/AES70Manager.cs:192)

When looking in the debugger, the issue is that NetworkChange on line 224 in ServiceBrowser.cs is null for some reason when I try to run it under Unity (I imported all of the sources in so that I could debug it. I've not seen this issue before where something runs differently from a normal windows build to a Unity build.

**Comment by tmds** [comment] 2019-04-27 19:24
For some reason, the native method: CreateNLSocket can't be found. This should be part of the mono bits used by unity. Is there a way for me to reproduce this? What version of unity are you using? What version of mono does that correspond to? Have you tried using the latest unity version?

**Comment by josephnarai** [comment] 2019-04-28 00:04
We are using the latest version of unity, 2019.1.0f2.

You can download the personal version for free.

I can make a simple test project for you tomorrow if that helps?

Thanks for looking into it for me, it's the last IP infrastructure component I need for a project I'm working on!

Kind regards,

Joseph

Joseph Narai

Sent from my phone

________________________________

**Comment by josephnarai** [comment] 2019-04-29 01:41
[TmdsMDnsBonjourTest.zip](https://github.com/tmds/Tmds.MDns/files/3125762/TmdsMDnsBonjourTest.zip)
Here is a simple Unity project. You should be able to open it and run in Unity 2019.1.0f2.

I've included all the source code in this example, however I've also tried just including the build .dll from your repo, but it had the same issue.

Please let me know if there is anything else I can do to help you track this down.

Kind Regards,

Joseph

**Comment by josephnarai** [comment] 2019-04-29 02:14
I've just tested in Unity on macOS and it works there!

**Comment by josephnarai** [comment] 2019-04-29 02:19
Unfortunately it also crashes on iOS. Call stack on crash is in the attached text file if it helps!

[BonjourTestDebugOutput.txt](https://github.com/tmds/Tmds.MDns/files/3125798/BonjourTestDebugOutput.txt)

Seems to be in the setsocketoption code.

The thing to note about running on iOS is that Unity uses the Il2cpp compiler, so the call stack output in the file is from the generated c++ code in xCode.

Again, please let me know if there is anything else I can do to help track down the issue for both iOS and Windows Unity operation!

**Comment by tmds** [comment] 2019-04-29 09:24
I'm going to have a look at this, but it may take some time.

> if there is anything else I can do to help track down the issue for both iOS and Windows Unity operation!

You can try to reproduce this with a simple program using Network.NetworkAddressChanged Event and report an issue with mono/unity.

**Comment by josephnarai** [comment] 2019-04-29 12:34
Can you elaborate on what exactly the simple program needs to do?

I'm happy to build and test it and can then report it, hot in not familiar enough with what I'm trying to repo.

Any more info would be appreciated.

Joseph Narai

Sent from my phone

________________________________

**Comment by tmds** [comment] 2019-04-29 13:40
The issue seems to take place when Tmds.MDns uses:
System.Net.NetworkInformation.NetworkChange.add_NetworkAddressChanged 
That is: a handler is added to this event: https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.networkchange.networkaddresschanged?view=netframework-4.8
So if you try the sample program from the documentation it will probably crash in the same way.

**Comment by josephnarai** [comment] 2019-04-29 21:09
Great, thanks for the explanation, I'll try out out and let you know how I get on

J

Joseph Narai

Sent from my phone

________________________________

**Comment by josephnarai** [comment] 2019-04-29 23:50
Indeed, it doesn't work under Unity.

I found this reference for OSX - but funnily enough, it works under OSX! https://bugzilla.xamarin.com/show_bug.cgi?id=12038

I'll post a question to Unity support and see what they say about it.

Kind Regards,

J

Joseph Narai | CTO | Monarc Media Labs Pty Ltd | Mob:  +61 (0)419 800 111 | www.monarc.media<http://www.monarc.media/> |

PRIVATE AND CONFIDENTIAL
This message and any attachments to it is intended for the use of the individual or entity to whom it is addressed by the first sender and contains information which may be confidential and/or privileged. If you receive this message and any attachment in error, please delete it immediately and notify the sender by electronic mail. Unless you have been expressly authorised by the sender, you are prohibited from copying, distributing or using the information contained in this message and any attachment.

On 30/04/2019 7:09:05 AM, Joseph Narai <josephn@monarc.media> wrote:

Great, thanks for the explanation, I'll try out out and let you know how I get on

J

Joseph Narai

Sent from my phone

________________________________

**Comment by swiftHao1108** [comment] 2019-06-12 07:57
how could i add this library to window qt c++ Platform ?
could you give me some tips ? thanks you !

**Comment by tmds** [comment] 2019-06-12 08:10
@swiftHao1108 try finding a native C/C++ library. It will be simpler to add that, than trying to integrate your qt c++ app with .NET.

**Comment by tmds** [comment] 2019-06-12 08:11
Closing the issue, root cause is in unity.

**Closed by tmds** 2019-06-12 08:11 UTC
