### ISSUE TITLE
Address reuse problem on C# Linux

### ISSUE THREAD

**Issue by QTimort** [tmds/Tmds.MDns#28] opened 2018-08-21 12:05 UTC
Hello @tmds,

There is a known problem with C# on Linux regarding port re-usability when binding a socket.
You have the same problem as another mdns C# library here: https://github.com/richardschneider/net-mdns/issues/22
Can you try to investigate this solution https://github.com/QTimort/bind-reuse-port and implement it so your library can be usable on Linux ?

**Comment by tmds** [comment] 2018-08-21 14:49
hi @QTimort 

Tmds.MDns calls
```
_socket.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, true);
```
on Linux, using .NET Core 2.1.302, this results in SO_REUSEPORT being set:
```
setsockopt(38, SOL_SOCKET, SO_REUSEPORT, [1], 4) = 0
```
I can run multiple instances of Tmds.MDns on my system.
Probably some other program has already exclusively claimed the port.

Maybe netstat can help you find out who is using mdns (e.g. `netstat -lup | grep mdns`).

**Comment by QTimort** [comment] 2018-08-21 15:04
Hi @tmds 
C# on Linux does set SO_REUSEPORT but it doesn't set SO_REUSEADDRESS which is needed to bind to an address already in use.
The solution I provided does work even though Chrome and Avahi are bound to the mdns port 5353.

To summarize your library work if we close any program bound to this port but it wouldn't be needed with the solution I linked which is not that hard to implement because I already modified your library so it use this solution and it work like a charm on Linux/Windows.

I basically replaced one call to socket.bind with 
`SocketBind.Bind(socket, new IPEndPoint(IPAddress.Any, port));`
like provided here https://github.com/QTimort/bind-reuse-port/blob/master/example/Program.cs#L17.

**Comment by QTimort** [comment] 2018-08-21 15:38
If you are on Linux using dotnetcore for example and have Avahi and or Chrome running (because they are both bound to port 5353) you should get a socket exception when trying to bind exactly here https://github.com/tmds/Tmds.MDns/blob/master/src/Tmds.MDns/NetworkInterfaceHandler.cs#L73

**Comment by tmds** [comment] 2018-08-21 15:47
I have avahi, chromium and two dotnet instances; all using mdns:
```
$ sudo lsof -i :5353
COMMAND     PID  USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
avahi-dae   955 avahi   15u  IPv4   16009      0t0  UDP *:mdns 
avahi-dae   955 avahi   16u  IPv6   16010      0t0  UDP *:mdns 
chromium-  2939  tmds  402u  IPv4 2103418      0t0  UDP *:mdns 
chromium-  2939  tmds  444u  IPv6 2103419      0t0  UDP *:mdns 
chromium-  2939  tmds  445u  IPv4 2103420      0t0  UDP *:mdns 
chromium-  2939  tmds  448u  IPv4 2103421      0t0  UDP *:mdns 
chromium-  2939  tmds  449u  IPv4 2103422      0t0  UDP *:mdns 
chromium-  2939  tmds  453u  IPv6 2103423      0t0  UDP *:mdns 
chromium-  2939  tmds  456u  IPv6 2103424      0t0  UDP *:mdns 
chromium-  2939  tmds  459u  IPv6 2103425      0t0  UDP *:mdns 
dotnet    12013  tmds   38u  IPv4 2766139      0t0  UDP *:mdns 
dotnet    12013  tmds   42u  IPv4 2766143      0t0  UDP *:mdns 
dotnet    12013  tmds   43u  IPv4 2766144      0t0  UDP *:mdns 
dotnet    25128  tmds   38u  IPv4 3148759      0t0  UDP *:mdns 
dotnet    25128  tmds   42u  IPv4 3148763      0t0  UDP *:mdns 
dotnet    25128  tmds   43u  IPv4 3148764      0t0  UDP *:mdns 
```

**Comment by QTimort** [comment] 2018-08-21 15:50
And you don't have any problem ?
That's weird, I will try to investigate the problem on my side maybe I am doing something incorrect or we are not using the same version of a library or donet.

**Comment by tmds** [comment] 2018-08-21 15:54
That works without issues on my machine.

Do you have an exception stacktrace?

Can you run your application with strace and share the output? Do something like: `strace -f -e setsockopt,bind dotnet <app.dll>`?

**Comment by nmpribeiro** [comment] 2018-08-22 06:59
Hi @tmds I am @QTimort 's colleague :) so... here's the stack trace:
`Browsing for type: _workstation._tcp

Unhandled Exception: System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Tmds.MDns.NetworkInterfaceHandler.Enable(Int32 port) in /home/unitelabs/unitelabs/csharp/csharp_pocs/HelloWorld/Tmds.MDns/NetworkInterfaceHandler.cs:line 73
   at Tmds.MDns.ServiceBrowser.CheckNetworkInterfaceStatuses(Dictionary`2 interfaceHandlers) in /home/unitelabs/unitelabs/csharp/csharp_pocs/HelloWorld/Tmds.MDns/ServiceBrowser.cs:line 270
   at Tmds.MDns.ServiceBrowser.StartBrowsing(SynchronizationContext synchronizationContext) in /home/unitelabs/unitelabs/csharp/csharp_pocs/HelloWorld/Tmds.MDns/ServiceBrowser.cs:line 228
   at Tmds.MDns.ServiceBrowser.StartBrowse(IEnumerable`1 serviceTypes, SynchronizationContext synchronizationContext) in /home/unitelabs/unitelabs/csharp/csharp_pocs/HelloWorld/Tmds.MDns/ServiceBrowser.cs:line 47
   at Tmds.MDns.ServiceBrowser.StartBrowse(IEnumerable`1 serviceTypes, Boolean useSynchronizationContext) in /home/unitelabs/unitelabs/csharp/csharp_pocs/HelloWorld/Tmds.MDns/ServiceBrowser.cs:line 76
   at Tmds.MDns.ServiceBrowser.StartBrowse(String serviceType, Boolean useSynchronizationContext) in /home/unitelabs/unitelabs/csharp/csharp_pocs/HelloWorld/Tmds.MDns/ServiceBrowser.cs:line 86
   at csharp_pocs.Program.Main(String[] args) in /home/unitelabs/unitelabs/csharp/csharp_pocs/HelloWorld/Program.cs:line 26
bash: line 1: 29259 Aborted                 /usr/share/dotnet/dotnet "/home/unitelabs/unitelabs/csharp/csharp_pocs/HelloWorld/bin/Debug/netcoreapp2.1/csharp_pocs.dll"

Press any key to continue...
`

`using System;
using Tmds.MDns;

namespace csharp_pocs
{
    class Program
    {
        static void Main(string[] args)
       {
			// Simple packet test:
			// SimplePacketTest simplePacketTest = new SimplePacketTest();

			// mDNS:
			string serviceType = "_workstation._tcp";
            if (args.Length >= 1)
            {
                serviceType = args[0];
            }

            ServiceBrowser serviceBrowser = new ServiceBrowser();
            serviceBrowser.ServiceAdded += onServiceAdded;
            serviceBrowser.ServiceRemoved += onServiceRemoved;
            serviceBrowser.ServiceChanged += onServiceChanged;

            Console.WriteLine("Browsing for type: {0}", serviceType);
            serviceBrowser.StartBrowse(serviceType);
            Console.ReadLine();
       }

		static void onServiceChanged(object sender, ServiceAnnouncementEventArgs e)
        {
            printService('~', e.Announcement);
        }

        static void onServiceRemoved(object sender, ServiceAnnouncementEventArgs e)
        {
            printService('-', e.Announcement);
        }

        static void onServiceAdded(object sender, ServiceAnnouncementEventArgs e)
        {
            printService('+', e.Announcement);
        }

        static void printService(char startChar, ServiceAnnouncement service)
        {
            Console.WriteLine("{0} '{1}' on {2}", startChar, service.Instance, service.NetworkInterface.Name);
            Console.WriteLine("\tHost: {0} ({1})", service.Hostname, string.Join(", ", service.Addresses));
            Console.WriteLine("\tPort: {0}", service.Port);
            Console.WriteLine("\tTxt : [{0}]", string.Join(", ", service.Txt));
        }
    }
}
`
➜ dotnet --version
2.1.400

With stack trace (command you supplied):
`Browsing for type: _workstation._tcp
[pid 29522] bind(26, {sa_family=AF_NETLINK, pid=0, groups=00000451}, 12) = 0
strace: Process 29530 attached
[pid 29522] bind(28, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 0
[pid 29509] +++ exited with 0 +++
[pid 29522] setsockopt(37, SOL_SOCKET, SO_REUSEPORT, [1], 4) = 0
[pid 29522] setsockopt(37, SOL_IP, IP_MULTICAST_IF, "\0\0\0\0\0\0\0\0\3\0\0\0", 12) = 0
[pid 29522] bind(37, {sa_family=AF_INET, sin_port=htons(5353), sin_addr=inet_addr("0.0.0.0")}, 16) = -1 EADDRINUSE (Address already in use)

Unhandled Exception: System.Net.Sockets.SocketException: Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Tmds.MDns.NetworkInterfaceHandler.Enable(Int32 port) in /home/unitelabs/unitelabs/csharp/csharp_pocs/HelloWorld/Tmds.MDns/NetworkInterfaceHandler.cs:line 73
   at Tmds.MDns.ServiceBrowser.CheckNetworkInterfaceStatuses(Dictionary`2 interfaceHandlers) in /home/unitelabs/unitelabs/csharp/csharp_pocs/HelloWorld/Tmds.MDns/ServiceBrowser.cs:line 270
   at Tmds.MDns.ServiceBrowser.StartBrowsing(SynchronizationContext synchronizationContext) in /home/unitelabs/unitelabs/csharp/csharp_pocs/HelloWorld/Tmds.MDns/ServiceBrowser.cs:line 228
   at Tmds.MDns.ServiceBrowser.StartBrowse(IEnumerable`1 serviceTypes, SynchronizationContext synchronizationContext) in /home/unitelabs/unitelabs/csharp/csharp_pocs/HelloWorld/Tmds.MDns/ServiceBrowser.cs:line 47
   at Tmds.MDns.ServiceBrowser.StartBrowse(IEnumerable`1 serviceTypes, Boolean useSynchronizationContext) in /home/unitelabs/unitelabs/csharp/csharp_pocs/HelloWorld/Tmds.MDns/ServiceBrowser.cs:line 76
   at Tmds.MDns.ServiceBrowser.StartBrowse(String serviceType, Boolean useSynchronizationContext) in /home/unitelabs/unitelabs/csharp/csharp_pocs/HelloWorld/Tmds.MDns/ServiceBrowser.cs:line 86
   at csharp_pocs.Program.Main(String[] args) in /home/unitelabs/unitelabs/csharp/csharp_pocs/HelloWorld/Program.cs:line 26
[pid 29522] --- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=29522, si_uid=1000} ---
[pid 29530] +++ killed by SIGABRT +++
`

**Comment by tmds** [comment] 2018-08-23 11:09
@nmpribeiro if you terminate all users of the mdns port (chrome, avahi, ...), can you then run two instances of the console application?

**Comment by nmpribeiro** [comment] 2018-08-23 11:38
@tmds if I terminate all users of the mdns port, then I can have two instances of the console application working. That is correct.

**Comment by tmds** [comment] 2018-08-23 12:45
And what program causes it to stop working? avahi, chrome, ...?

**Comment by nmpribeiro** [comment] 2018-08-23 13:01
Both avahi AND/OR chrome.

**Comment by tmds** [comment] 2018-08-23 13:04
What flavor of Linux are you using?
And versions of avahi and chrome?

**Comment by QTimort** [comment] 2018-08-23 13:14
For me:
Ubuntu 18.04 Bionic (x86-64)
Linux Kernel: 4.15.0.32-generic

Chromium 68.0.3440.106 
Avahi 0.7

**Comment by tmds** [comment] 2018-08-23 15:11
I'm on Fedora 28.
avahi: 0.7-12
chromium: 67.0.3396
linux: 4.16.16

I'll try to reproduce what you're seeing in a VM.

**Comment by nmpribeiro** [comment] 2018-08-23 15:15
Fedora is actually an rpm dist... might have different socket implementation. Please let us know your findings. I can try also on my fedora at home later or tomorrow (perhaps).

**Comment by nmpribeiro** [comment] 2018-08-23 15:25
I wonder which improvements were made to the LNX kernel from 4.15 to 4.16

**Comment by tmds** [comment] 2018-08-31 12:52
Someone has reported a similar issue in corefx: https://github.com/dotnet/corefx/issues/32027. The root cause is: if one process only sets SO_REUSEADDR and another only sets SO_REUSEPORT, the second application will fail to bind. The fix is to make .NET Core set both options.

I think on your system avahi/chrome may be compiled without SO_REUSEPORT, e.g.: https://github.com/lathiat/avahi/blob/a81407c67d9d9b3bc656920760fb425c0d79466b/avahi-core/socket.c#L176-L183 which explains the different behavior between your Ubuntu and my Fedora 28.

**Comment by tmds** [comment] 2019-04-27 19:25
This should be fixed in .net core 3.0.

**Closed** 2019-06-12 08:11 UTC
